#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 jmlich
# Login shell of the panel user. When panel.py ends, the login ends and
# getty starts it again.

exec /opt/panel/venv/bin/python3 /opt/panel/panel.py
